name: thesis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - cpuonly        # omit for GPU
  - numpy
  - pandas
  - tsdm
  - matplotlib     # optional
  - notebook       # optional
  - pip
